services:
  - type: web
    name: hyper-chat-app
    env: php
    buildCommand: composer install
    startCommand: heroku-php-apache2 .
    envVars:
      - key: FIREBASE_API_KEY
        value: AIzaSyA680lTlCSZlyJltI7Rf_mEQywJqNhrXMo
      - key: FIREBASE_AUTH_DOMAIN
        value: hyperchatapp-d73c6.firebaseapp.com
      - key: FIREBASE_PROJECT_ID
        value: hyperchatapp-d73c6
      - key: FIREBASE_STORAGE_BUCKET
        value: hyperchatapp-d73c6.appspot.com
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: 128236799823
      - key: FIREBASE_APP_ID
        value: 1:128236799823:web:8a788805aea85626c9673a
      - key: FIREBASE_MEASUREMENT_ID
        value: G-VS7CYFT99G
